**Metoda najmniejszych kwadratów**

In [2]:
import numpy as np
import scipy
import matplotlib.pyplot as plt
import pandas as pd

**Zadanie 1.**

In [8]:
train_file = "conspect/dataset/breast-cancer-train.dat"
validate_file = "conspect/dataset/breast-cancer-validate.dat"
train = pd.io.parsers.read_csv(train_file, header=None)
validate = pd.io.parsers.read_csv(validate_file, header=None)
# train.iloc[:,2].hist()
# plt.show()
# train.iloc[:,2].plot()
# train
A_lin = np.matrix(train.iloc[:,2:])

print(A_lin)


[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.176e+01 1.814e+01 7.500e+01 ... 7.160e-02 1.978e-01 6.915e-02]
 [1.426e+01 1.817e+01 9.122e+01 ... 7.530e-02 2.636e-01 7.676e-02]
 [1.051e+01 2.309e+01 6.685e+01 ... 3.125e-02 2.227e-01 6.777e-02]]
